// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: configsync/v1/configsync.proto

package configsync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                        // gateway's last-applied version; 0 = full resync
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`             // stable per-process identifier (survives reconnects)
	AppVersion    string                 `protobuf:"bytes,3,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"` // gateway build version, for node visibility
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`                       // gateway's os.Hostname(), for node visibility
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{0}
}

func (x *Subscribe) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Subscribe) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Subscribe) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *Subscribe) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

// ConfigSnapshot is a full, immutable configuration snapshot (config-schema:
// upstreams/routes/consumers). The gateway swaps its in-memory ConfigCache
// atomically on each received snapshot. Full-snapshot push (not incremental):
// small config, atomic swap, no merge bugs. The version field is the hook for
// future delta support.
type ConfigSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Upstreams     []*Upstream            `protobuf:"bytes,2,rep,name=upstreams,proto3" json:"upstreams,omitempty"`
	Routes        []*Route               `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	Consumers     []*Consumer            `protobuf:"bytes,4,rep,name=consumers,proto3" json:"consumers,omitempty"`
	Settings      map[string]string      `protobuf:"bytes,5,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSnapshot) Reset() {
	*x = ConfigSnapshot{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSnapshot) ProtoMessage() {}

func (x *ConfigSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSnapshot.ProtoReflect.Descriptor instead.
func (*ConfigSnapshot) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigSnapshot) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigSnapshot) GetUpstreams() []*Upstream {
	if x != nil {
		return x.Upstreams
	}
	return nil
}

func (x *ConfigSnapshot) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *ConfigSnapshot) GetConsumers() []*Consumer {
	if x != nil {
		return x.Consumers
	}
	return nil
}

func (x *ConfigSnapshot) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

type Upstream struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Protocol        string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	BaseUrl         string                 `protobuf:"bytes,5,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	CredentialsJson string                 `protobuf:"bytes,6,opt,name=credentials_json,json=credentialsJson,proto3" json:"credentials_json,omitempty"`
	ModelsJson      string                 `protobuf:"bytes,7,opt,name=models_json,json=modelsJson,proto3" json:"models_json,omitempty"`
	ProxyUrl        string                 `protobuf:"bytes,8,opt,name=proxy_url,json=proxyUrl,proto3" json:"proxy_url,omitempty"`
	Enabled         bool                   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Upstream) Reset() {
	*x = Upstream{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Upstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upstream) ProtoMessage() {}

func (x *Upstream) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upstream.ProtoReflect.Descriptor instead.
func (*Upstream) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{2}
}

func (x *Upstream) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Upstream) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Upstream) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Upstream) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Upstream) GetCredentialsJson() string {
	if x != nil {
		return x.CredentialsJson
	}
	return ""
}

func (x *Upstream) GetModelsJson() string {
	if x != nil {
		return x.ModelsJson
	}
	return ""
}

func (x *Upstream) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

func (x *Upstream) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type RouteUpstream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RouteId       string                 `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	UpstreamId    string                 `protobuf:"bytes,3,opt,name=upstream_id,json=upstreamId,proto3" json:"upstream_id,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Weight        int32                  `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Enabled       bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteUpstream) Reset() {
	*x = RouteUpstream{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteUpstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteUpstream) ProtoMessage() {}

func (x *RouteUpstream) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteUpstream.ProtoReflect.Descriptor instead.
func (*RouteUpstream) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{3}
}

func (x *RouteUpstream) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RouteUpstream) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *RouteUpstream) GetUpstreamId() string {
	if x != nil {
		return x.UpstreamId
	}
	return ""
}

func (x *RouteUpstream) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RouteUpstream) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *RouteUpstream) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RouteUpstream) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Balance       string                 `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	EnableAuth    bool                   `protobuf:"varint,4,opt,name=enable_auth,json=enableAuth,proto3" json:"enable_auth,omitempty"`
	EnablePayload bool                   `protobuf:"varint,5,opt,name=enable_payload,json=enablePayload,proto3" json:"enable_payload,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Targets       []*RouteUpstream       `protobuf:"bytes,7,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{4}
}

func (x *Route) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Route) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Route) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *Route) GetEnableAuth() bool {
	if x != nil {
		return x.EnableAuth
	}
	return false
}

func (x *Route) GetEnablePayload() bool {
	if x != nil {
		return x.EnablePayload
	}
	return false
}

func (x *Route) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Route) GetTargets() []*RouteUpstream {
	if x != nil {
		return x.Targets
	}
	return nil
}

// ConsumerKeyRef is the gateway-facing view of a consumer key: enough to
// authenticate a raw token locally (preview filter + hash compare) without ever
// carrying the plaintext token or DB-only bookkeeping fields (name, last_used_at).
type ConsumerKeyRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	KeyPreview    string                 `protobuf:"bytes,3,opt,name=key_preview,json=keyPreview,proto3" json:"key_preview,omitempty"`
	KeyHash       string                 `protobuf:"bytes,4,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerKeyRef) Reset() {
	*x = ConsumerKeyRef{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerKeyRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerKeyRef) ProtoMessage() {}

func (x *ConsumerKeyRef) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerKeyRef.ProtoReflect.Descriptor instead.
func (*ConsumerKeyRef) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{5}
}

func (x *ConsumerKeyRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConsumerKeyRef) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *ConsumerKeyRef) GetKeyPreview() string {
	if x != nil {
		return x.KeyPreview
	}
	return ""
}

func (x *ConsumerKeyRef) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

func (x *ConsumerKeyRef) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ConsumerKeyRef) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type ConsumerQuota struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	QuotaType     string                 `protobuf:"bytes,3,opt,name=quota_type,json=quotaType,proto3" json:"quota_type,omitempty"`
	QuotaLimit    int64                  `protobuf:"varint,4,opt,name=quota_limit,json=quotaLimit,proto3" json:"quota_limit,omitempty"`
	Window        string                 `protobuf:"bytes,5,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerQuota) Reset() {
	*x = ConsumerQuota{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerQuota) ProtoMessage() {}

func (x *ConsumerQuota) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerQuota.ProtoReflect.Descriptor instead.
func (*ConsumerQuota) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{6}
}

func (x *ConsumerQuota) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConsumerQuota) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *ConsumerQuota) GetQuotaType() string {
	if x != nil {
		return x.QuotaType
	}
	return ""
}

func (x *ConsumerQuota) GetQuotaLimit() int64 {
	if x != nil {
		return x.QuotaLimit
	}
	return 0
}

func (x *ConsumerQuota) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

type Consumer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Keys          []*ConsumerKeyRef      `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
	Routes        []string               `protobuf:"bytes,5,rep,name=routes,proto3" json:"routes,omitempty"` // granted route model names
	Quotas        []*ConsumerQuota       `protobuf:"bytes,6,rep,name=quotas,proto3" json:"quotas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consumer) Reset() {
	*x = Consumer{}
	mi := &file_configsync_v1_configsync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consumer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consumer) ProtoMessage() {}

func (x *Consumer) ProtoReflect() protoreflect.Message {
	mi := &file_configsync_v1_configsync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consumer.ProtoReflect.Descriptor instead.
func (*Consumer) Descriptor() ([]byte, []int) {
	return file_configsync_v1_configsync_proto_rawDescGZIP(), []int{7}
}

func (x *Consumer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Consumer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Consumer) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Consumer) GetKeys() []*ConsumerKeyRef {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *Consumer) GetRoutes() []string {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *Consumer) GetQuotas() []*ConsumerQuota {
	if x != nil {
		return x.Quotas
	}
	return nil
}

var File_configsync_v1_configsync_proto protoreflect.FileDescriptor

const file_configsync_v1_configsync_proto_rawDesc = "" +
	"\n" +
	"\x1econfigsync/v1/configsync.proto\x12\x12nyro.configsync.v1\"{\n" +
	"\tSubscribe\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vapp_version\x18\x03 \x01(\tR\n" +
	"appVersion\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\"\xe0\x02\n" +
	"\x0eConfigSnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12:\n" +
	"\tupstreams\x18\x02 \x03(\v2\x1c.nyro.configsync.v1.UpstreamR\tupstreams\x121\n" +
	"\x06routes\x18\x03 \x03(\v2\x19.nyro.configsync.v1.RouteR\x06routes\x12:\n" +
	"\tconsumers\x18\x04 \x03(\v2\x1c.nyro.configsync.v1.ConsumerR\tconsumers\x12L\n" +
	"\bsettings\x18\x05 \x03(\v20.nyro.configsync.v1.ConfigSnapshot.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe8\x01\n" +
	"\bUpstream\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x19\n" +
	"\bbase_url\x18\x05 \x01(\tR\abaseUrl\x12)\n" +
	"\x10credentials_json\x18\x06 \x01(\tR\x0fcredentialsJson\x12\x1f\n" +
	"\vmodels_json\x18\a \x01(\tR\n" +
	"modelsJson\x12\x1b\n" +
	"\tproxy_url\x18\b \x01(\tR\bproxyUrl\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\"\xbf\x01\n" +
	"\rRouteUpstream\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12\x1f\n" +
	"\vupstream_id\x18\x03 \x01(\tR\n" +
	"upstreamId\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\"\xe6\x01\n" +
	"\x05Route\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x18\n" +
	"\abalance\x18\x03 \x01(\tR\abalance\x12\x1f\n" +
	"\venable_auth\x18\x04 \x01(\bR\n" +
	"enableAuth\x12%\n" +
	"\x0eenable_payload\x18\x05 \x01(\bR\renablePayload\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12;\n" +
	"\atargets\x18\a \x03(\v2!.nyro.configsync.v1.RouteUpstreamR\atargets\"\xb6\x01\n" +
	"\x0eConsumerKeyRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\x12\x1f\n" +
	"\vkey_preview\x18\x03 \x01(\tR\n" +
	"keyPreview\x12\x19\n" +
	"\bkey_hash\x18\x04 \x01(\tR\akeyHash\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\tR\texpiresAt\"\x98\x01\n" +
	"\rConsumerQuota\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\x12\x1d\n" +
	"\n" +
	"quota_type\x18\x03 \x01(\tR\tquotaType\x12\x1f\n" +
	"\vquota_limit\x18\x04 \x01(\x03R\n" +
	"quotaLimit\x12\x16\n" +
	"\x06window\x18\x05 \x01(\tR\x06window\"\xd3\x01\n" +
	"\bConsumer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x126\n" +
	"\x04keys\x18\x04 \x03(\v2\".nyro.configsync.v1.ConsumerKeyRefR\x04keys\x12\x16\n" +
	"\x06routes\x18\x05 \x03(\tR\x06routes\x129\n" +
	"\x06quotas\x18\x06 \x03(\v2!.nyro.configsync.v1.ConsumerQuotaR\x06quotas2d\n" +
	"\rConfigService\x12S\n" +
	"\fStreamConfig\x12\x1d.nyro.configsync.v1.Subscribe\x1a\".nyro.configsync.v1.ConfigSnapshot0\x01B>Z<github.com/nyroway/nyro/go/internal/configsync/pb;configsyncb\x06proto3"

var (
	file_configsync_v1_configsync_proto_rawDescOnce sync.Once
	file_configsync_v1_configsync_proto_rawDescData []byte
)

func file_configsync_v1_configsync_proto_rawDescGZIP() []byte {
	file_configsync_v1_configsync_proto_rawDescOnce.Do(func() {
		file_configsync_v1_configsync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configsync_v1_configsync_proto_rawDesc), len(file_configsync_v1_configsync_proto_rawDesc)))
	})
	return file_configsync_v1_configsync_proto_rawDescData
}

var file_configsync_v1_configsync_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_configsync_v1_configsync_proto_goTypes = []any{
	(*Subscribe)(nil),      // 0: nyro.configsync.v1.Subscribe
	(*ConfigSnapshot)(nil), // 1: nyro.configsync.v1.ConfigSnapshot
	(*Upstream)(nil),       // 2: nyro.configsync.v1.Upstream
	(*RouteUpstream)(nil),  // 3: nyro.configsync.v1.RouteUpstream
	(*Route)(nil),          // 4: nyro.configsync.v1.Route
	(*ConsumerKeyRef)(nil), // 5: nyro.configsync.v1.ConsumerKeyRef
	(*ConsumerQuota)(nil),  // 6: nyro.configsync.v1.ConsumerQuota
	(*Consumer)(nil),       // 7: nyro.configsync.v1.Consumer
	nil,                    // 8: nyro.configsync.v1.ConfigSnapshot.SettingsEntry
}
var file_configsync_v1_configsync_proto_depIdxs = []int32{
	2, // 0: nyro.configsync.v1.ConfigSnapshot.upstreams:type_name -> nyro.configsync.v1.Upstream
	4, // 1: nyro.configsync.v1.ConfigSnapshot.routes:type_name -> nyro.configsync.v1.Route
	7, // 2: nyro.configsync.v1.ConfigSnapshot.consumers:type_name -> nyro.configsync.v1.Consumer
	8, // 3: nyro.configsync.v1.ConfigSnapshot.settings:type_name -> nyro.configsync.v1.ConfigSnapshot.SettingsEntry
	3, // 4: nyro.configsync.v1.Route.targets:type_name -> nyro.configsync.v1.RouteUpstream
	5, // 5: nyro.configsync.v1.Consumer.keys:type_name -> nyro.configsync.v1.ConsumerKeyRef
	6, // 6: nyro.configsync.v1.Consumer.quotas:type_name -> nyro.configsync.v1.ConsumerQuota
	0, // 7: nyro.configsync.v1.ConfigService.StreamConfig:input_type -> nyro.configsync.v1.Subscribe
	1, // 8: nyro.configsync.v1.ConfigService.StreamConfig:output_type -> nyro.configsync.v1.ConfigSnapshot
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_configsync_v1_configsync_proto_init() }
func file_configsync_v1_configsync_proto_init() {
	if File_configsync_v1_configsync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configsync_v1_configsync_proto_rawDesc), len(file_configsync_v1_configsync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_configsync_v1_configsync_proto_goTypes,
		DependencyIndexes: file_configsync_v1_configsync_proto_depIdxs,
		MessageInfos:      file_configsync_v1_configsync_proto_msgTypes,
	}.Build()
	File_configsync_v1_configsync_proto = out.File
	file_configsync_v1_configsync_proto_goTypes = nil
	file_configsync_v1_configsync_proto_depIdxs = nil
}
