// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: xds/v1/xds.proto

package xds

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // gateway's last-applied version; 0 = full resync
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_xds_v1_xds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_xds_v1_xds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_xds_v1_xds_proto_rawDescGZIP(), []int{0}
}

func (x *Subscribe) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// ConfigSnapshot is a full, immutable configuration snapshot. The gateway swaps
// its in-memory ConfigCache atomically on each received snapshot. Full-snapshot
// push (not incremental): small config, atomic swap, no merge bugs. The version
// field is the hook for future delta support.
type ConfigSnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Providers        []*Provider            `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`
	Models           []*Model               `protobuf:"bytes,3,rep,name=models,proto3" json:"models,omitempty"`
	ApiKeys          []*ApiKey              `protobuf:"bytes,4,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	OauthCredentials []*OAuthCredential     `protobuf:"bytes,5,rep,name=oauth_credentials,json=oauthCredentials,proto3" json:"oauth_credentials,omitempty"`
	Settings         map[string]string      `protobuf:"bytes,6,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigSnapshot) Reset() {
	*x = ConfigSnapshot{}
	mi := &file_xds_v1_xds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSnapshot) ProtoMessage() {}

func (x *ConfigSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_xds_v1_xds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSnapshot.ProtoReflect.Descriptor instead.
func (*ConfigSnapshot) Descriptor() ([]byte, []int) {
	return file_xds_v1_xds_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigSnapshot) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigSnapshot) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *ConfigSnapshot) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ConfigSnapshot) GetApiKeys() []*ApiKey {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

func (x *ConfigSnapshot) GetOauthCredentials() []*OAuthCredential {
	if x != nil {
		return x.OauthCredentials
	}
	return nil
}

func (x *ConfigSnapshot) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Vendor        string                 `protobuf:"bytes,3,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,5,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	PresetKey     string                 `protobuf:"bytes,6,opt,name=preset_key,json=presetKey,proto3" json:"preset_key,omitempty"`
	Channel       string                 `protobuf:"bytes,7,opt,name=channel,proto3" json:"channel,omitempty"`
	ModelsSource  string                 `protobuf:"bytes,8,opt,name=models_source,json=modelsSource,proto3" json:"models_source,omitempty"`
	StaticModels  string                 `protobuf:"bytes,9,opt,name=static_models,json=staticModels,proto3" json:"static_models,omitempty"`
	ApiKey        string                 `protobuf:"bytes,10,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	AuthMode      string                 `protobuf:"bytes,11,opt,name=auth_mode,json=authMode,proto3" json:"auth_mode,omitempty"`
	UseProxy      bool                   `protobuf:"varint,12,opt,name=use_proxy,json=useProxy,proto3" json:"use_proxy,omitempty"`
	IsEnabled     bool                   `protobuf:"varint,13,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_xds_v1_xds_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_xds_v1_xds_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_xds_v1_xds_proto_rawDescGZIP(), []int{2}
}

func (x *Provider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Provider) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *Provider) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Provider) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Provider) GetPresetKey() string {
	if x != nil {
		return x.PresetKey
	}
	return ""
}

func (x *Provider) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Provider) GetModelsSource() string {
	if x != nil {
		return x.ModelsSource
	}
	return ""
}

func (x *Provider) GetStaticModels() string {
	if x != nil {
		return x.StaticModels
	}
	return ""
}

func (x *Provider) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Provider) GetAuthMode() string {
	if x != nil {
		return x.AuthMode
	}
	return ""
}

func (x *Provider) GetUseProxy() bool {
	if x != nil {
		return x.UseProxy
	}
	return false
}

func (x *Provider) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

type ModelBackend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ProviderId    string                 `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Weight        int32                  `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelBackend) Reset() {
	*x = ModelBackend{}
	mi := &file_xds_v1_xds_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelBackend) ProtoMessage() {}

func (x *ModelBackend) ProtoReflect() protoreflect.Message {
	mi := &file_xds_v1_xds_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelBackend.ProtoReflect.Descriptor instead.
func (*ModelBackend) Descriptor() ([]byte, []int) {
	return file_xds_v1_xds_proto_rawDescGZIP(), []int{3}
}

func (x *ModelBackend) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelBackend) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelBackend) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ModelBackend) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelBackend) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ModelBackend) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Balance       string                 `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	EnableAuth    bool                   `protobuf:"varint,4,opt,name=enable_auth,json=enableAuth,proto3" json:"enable_auth,omitempty"`
	IsEnabled     bool                   `protobuf:"varint,5,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	Targets       []*ModelBackend        `protobuf:"bytes,6,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_xds_v1_xds_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_xds_v1_xds_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_xds_v1_xds_proto_rawDescGZIP(), []int{4}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *Model) GetEnableAuth() bool {
	if x != nil {
		return x.EnableAuth
	}
	return false
}

func (x *Model) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *Model) GetTargets() []*ModelBackend {
	if x != nil {
		return x.Targets
	}
	return nil
}

type ApiKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Rpm           *int32                 `protobuf:"varint,4,opt,name=rpm,proto3,oneof" json:"rpm,omitempty"`
	Rpd           *int32                 `protobuf:"varint,5,opt,name=rpd,proto3,oneof" json:"rpd,omitempty"`
	Tpm           *int32                 `protobuf:"varint,6,opt,name=tpm,proto3,oneof" json:"tpm,omitempty"`
	Tpd           *int32                 `protobuf:"varint,7,opt,name=tpd,proto3,oneof" json:"tpd,omitempty"`
	IsEnabled     bool                   `protobuf:"varint,8,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	BoundModelIds []string               `protobuf:"bytes,10,rep,name=bound_model_ids,json=boundModelIds,proto3" json:"bound_model_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKey) Reset() {
	*x = ApiKey{}
	mi := &file_xds_v1_xds_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKey) ProtoMessage() {}

func (x *ApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_xds_v1_xds_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKey.ProtoReflect.Descriptor instead.
func (*ApiKey) Descriptor() ([]byte, []int) {
	return file_xds_v1_xds_proto_rawDescGZIP(), []int{5}
}

func (x *ApiKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiKey) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ApiKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiKey) GetRpm() int32 {
	if x != nil && x.Rpm != nil {
		return *x.Rpm
	}
	return 0
}

func (x *ApiKey) GetRpd() int32 {
	if x != nil && x.Rpd != nil {
		return *x.Rpd
	}
	return 0
}

func (x *ApiKey) GetTpm() int32 {
	if x != nil && x.Tpm != nil {
		return *x.Tpm
	}
	return 0
}

func (x *ApiKey) GetTpd() int32 {
	if x != nil && x.Tpd != nil {
		return *x.Tpd
	}
	return 0
}

func (x *ApiKey) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *ApiKey) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *ApiKey) GetBoundModelIds() []string {
	if x != nil {
		return x.BoundModelIds
	}
	return nil
}

type OAuthCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	DriverKey     string                 `protobuf:"bytes,2,opt,name=driver_key,json=driverKey,proto3" json:"driver_key,omitempty"`
	Scheme        string                 `protobuf:"bytes,3,opt,name=scheme,proto3" json:"scheme,omitempty"`
	AccessToken   string                 `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,5,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	StatusVersion int32                  `protobuf:"varint,7,opt,name=status_version,json=statusVersion,proto3" json:"status_version,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthCredential) Reset() {
	*x = OAuthCredential{}
	mi := &file_xds_v1_xds_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthCredential) ProtoMessage() {}

func (x *OAuthCredential) ProtoReflect() protoreflect.Message {
	mi := &file_xds_v1_xds_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthCredential.ProtoReflect.Descriptor instead.
func (*OAuthCredential) Descriptor() ([]byte, []int) {
	return file_xds_v1_xds_proto_rawDescGZIP(), []int{6}
}

func (x *OAuthCredential) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *OAuthCredential) GetDriverKey() string {
	if x != nil {
		return x.DriverKey
	}
	return ""
}

func (x *OAuthCredential) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *OAuthCredential) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *OAuthCredential) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OAuthCredential) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *OAuthCredential) GetStatusVersion() int32 {
	if x != nil {
		return x.StatusVersion
	}
	return 0
}

func (x *OAuthCredential) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_xds_v1_xds_proto protoreflect.FileDescriptor

const file_xds_v1_xds_proto_rawDesc = "" +
	"\n" +
	"\x10xds/v1/xds.proto\x12\vnyro.xds.v1\"%\n" +
	"\tSubscribe\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\"\x8a\x03\n" +
	"\x0eConfigSnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x123\n" +
	"\tproviders\x18\x02 \x03(\v2\x15.nyro.xds.v1.ProviderR\tproviders\x12*\n" +
	"\x06models\x18\x03 \x03(\v2\x12.nyro.xds.v1.ModelR\x06models\x12.\n" +
	"\bapi_keys\x18\x04 \x03(\v2\x13.nyro.xds.v1.ApiKeyR\aapiKeys\x12I\n" +
	"\x11oauth_credentials\x18\x05 \x03(\v2\x1c.nyro.xds.v1.OAuthCredentialR\x10oauthCredentials\x12E\n" +
	"\bsettings\x18\x06 \x03(\v2).nyro.xds.v1.ConfigSnapshot.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf2\x02\n" +
	"\bProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06vendor\x18\x03 \x01(\tR\x06vendor\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x19\n" +
	"\bbase_url\x18\x05 \x01(\tR\abaseUrl\x12\x1d\n" +
	"\n" +
	"preset_key\x18\x06 \x01(\tR\tpresetKey\x12\x18\n" +
	"\achannel\x18\a \x01(\tR\achannel\x12#\n" +
	"\rmodels_source\x18\b \x01(\tR\fmodelsSource\x12#\n" +
	"\rstatic_models\x18\t \x01(\tR\fstaticModels\x12\x17\n" +
	"\aapi_key\x18\n" +
	" \x01(\tR\x06apiKey\x12\x1b\n" +
	"\tauth_mode\x18\v \x01(\tR\bauthMode\x12\x1b\n" +
	"\tuse_proxy\x18\f \x01(\bR\buseProxy\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\r \x01(\bR\tisEnabled\"\xa4\x01\n" +
	"\fModelBackend\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\tR\n" +
	"providerId\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\"\xba\x01\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\abalance\x18\x03 \x01(\tR\abalance\x12\x1f\n" +
	"\venable_auth\x18\x04 \x01(\bR\n" +
	"enableAuth\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\x05 \x01(\bR\tisEnabled\x123\n" +
	"\atargets\x18\x06 \x03(\v2\x19.nyro.xds.v1.ModelBackendR\atargets\"\xa4\x02\n" +
	"\x06ApiKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x15\n" +
	"\x03rpm\x18\x04 \x01(\x05H\x00R\x03rpm\x88\x01\x01\x12\x15\n" +
	"\x03rpd\x18\x05 \x01(\x05H\x01R\x03rpd\x88\x01\x01\x12\x15\n" +
	"\x03tpm\x18\x06 \x01(\x05H\x02R\x03tpm\x88\x01\x01\x12\x15\n" +
	"\x03tpd\x18\a \x01(\x05H\x03R\x03tpd\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\b \x01(\bR\tisEnabled\x12\x1d\n" +
	"\n" +
	"expires_at\x18\t \x01(\tR\texpiresAt\x12&\n" +
	"\x0fbound_model_ids\x18\n" +
	" \x03(\tR\rboundModelIdsB\x06\n" +
	"\x04_rpmB\x06\n" +
	"\x04_rpdB\x06\n" +
	"\x04_tpmB\x06\n" +
	"\x04_tpd\"\x8f\x02\n" +
	"\x0fOAuthCredential\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x1d\n" +
	"\n" +
	"driver_key\x18\x02 \x01(\tR\tdriverKey\x12\x16\n" +
	"\x06scheme\x18\x03 \x01(\tR\x06scheme\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x05 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\tR\texpiresAt\x12%\n" +
	"\x0estatus_version\x18\a \x01(\x05R\rstatusVersion\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status2V\n" +
	"\rConfigService\x12E\n" +
	"\fStreamConfig\x12\x16.nyro.xds.v1.Subscribe\x1a\x1b.nyro.xds.v1.ConfigSnapshot0\x01B0Z.github.com/nyroway/nyro/go/internal/xds/pb;xdsb\x06proto3"

var (
	file_xds_v1_xds_proto_rawDescOnce sync.Once
	file_xds_v1_xds_proto_rawDescData []byte
)

func file_xds_v1_xds_proto_rawDescGZIP() []byte {
	file_xds_v1_xds_proto_rawDescOnce.Do(func() {
		file_xds_v1_xds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xds_v1_xds_proto_rawDesc), len(file_xds_v1_xds_proto_rawDesc)))
	})
	return file_xds_v1_xds_proto_rawDescData
}

var file_xds_v1_xds_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_xds_v1_xds_proto_goTypes = []any{
	(*Subscribe)(nil),       // 0: nyro.xds.v1.Subscribe
	(*ConfigSnapshot)(nil),  // 1: nyro.xds.v1.ConfigSnapshot
	(*Provider)(nil),        // 2: nyro.xds.v1.Provider
	(*ModelBackend)(nil),    // 3: nyro.xds.v1.ModelBackend
	(*Model)(nil),           // 4: nyro.xds.v1.Model
	(*ApiKey)(nil),          // 5: nyro.xds.v1.ApiKey
	(*OAuthCredential)(nil), // 6: nyro.xds.v1.OAuthCredential
	nil,                     // 7: nyro.xds.v1.ConfigSnapshot.SettingsEntry
}
var file_xds_v1_xds_proto_depIdxs = []int32{
	2, // 0: nyro.xds.v1.ConfigSnapshot.providers:type_name -> nyro.xds.v1.Provider
	4, // 1: nyro.xds.v1.ConfigSnapshot.models:type_name -> nyro.xds.v1.Model
	5, // 2: nyro.xds.v1.ConfigSnapshot.api_keys:type_name -> nyro.xds.v1.ApiKey
	6, // 3: nyro.xds.v1.ConfigSnapshot.oauth_credentials:type_name -> nyro.xds.v1.OAuthCredential
	7, // 4: nyro.xds.v1.ConfigSnapshot.settings:type_name -> nyro.xds.v1.ConfigSnapshot.SettingsEntry
	3, // 5: nyro.xds.v1.Model.targets:type_name -> nyro.xds.v1.ModelBackend
	0, // 6: nyro.xds.v1.ConfigService.StreamConfig:input_type -> nyro.xds.v1.Subscribe
	1, // 7: nyro.xds.v1.ConfigService.StreamConfig:output_type -> nyro.xds.v1.ConfigSnapshot
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_xds_v1_xds_proto_init() }
func file_xds_v1_xds_proto_init() {
	if File_xds_v1_xds_proto != nil {
		return
	}
	file_xds_v1_xds_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xds_v1_xds_proto_rawDesc), len(file_xds_v1_xds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xds_v1_xds_proto_goTypes,
		DependencyIndexes: file_xds_v1_xds_proto_depIdxs,
		MessageInfos:      file_xds_v1_xds_proto_msgTypes,
	}.Build()
	File_xds_v1_xds_proto = out.File
	file_xds_v1_xds_proto_goTypes = nil
	file_xds_v1_xds_proto_depIdxs = nil
}
