// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/nyroway/nyro/go/internal/storage/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newConsumer(db *gorm.DB, opts ...gen.DOOption) consumer {
	_consumer := consumer{}

	_consumer.consumerDo.UseDB(db, opts...)
	_consumer.consumerDo.UseModel(&model.Consumer{})

	tableName := _consumer.consumerDo.TableName()
	_consumer.ALL = field.NewAsterisk(tableName)
	_consumer.ID = field.NewString(tableName, "id")
	_consumer.Name = field.NewString(tableName, "name")
	_consumer.Enabled = field.NewBool(tableName, "enabled")
	_consumer.MetadataJSON = field.NewString(tableName, "metadata_json")
	_consumer.ProtocolsJSON = field.NewString(tableName, "protocols_json")
	_consumer.IPAllowlistJSON = field.NewString(tableName, "ip_allowlist_json")
	_consumer.MaxInputTokens = field.NewInt64(tableName, "max_input_tokens")
	_consumer.MaxOutputTokens = field.NewInt64(tableName, "max_output_tokens")
	_consumer.MaxRequestBodyBytes = field.NewInt64(tableName, "max_request_body_bytes")
	_consumer.CreatedAt = field.NewString(tableName, "created_at")
	_consumer.UpdatedAt = field.NewString(tableName, "updated_at")

	_consumer.fillFieldMap()

	return _consumer
}

type consumer struct {
	consumerDo consumerDo

	ALL                 field.Asterisk
	ID                  field.String
	Name                field.String
	Enabled             field.Bool
	MetadataJSON        field.String
	ProtocolsJSON       field.String
	IPAllowlistJSON     field.String
	MaxInputTokens      field.Int64
	MaxOutputTokens     field.Int64
	MaxRequestBodyBytes field.Int64
	CreatedAt           field.String
	UpdatedAt           field.String

	fieldMap map[string]field.Expr
}

func (c consumer) Table(newTableName string) *consumer {
	c.consumerDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c consumer) As(alias string) *consumer {
	c.consumerDo.DO = *(c.consumerDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *consumer) updateTableName(table string) *consumer {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.Name = field.NewString(table, "name")
	c.Enabled = field.NewBool(table, "enabled")
	c.MetadataJSON = field.NewString(table, "metadata_json")
	c.ProtocolsJSON = field.NewString(table, "protocols_json")
	c.IPAllowlistJSON = field.NewString(table, "ip_allowlist_json")
	c.MaxInputTokens = field.NewInt64(table, "max_input_tokens")
	c.MaxOutputTokens = field.NewInt64(table, "max_output_tokens")
	c.MaxRequestBodyBytes = field.NewInt64(table, "max_request_body_bytes")
	c.CreatedAt = field.NewString(table, "created_at")
	c.UpdatedAt = field.NewString(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *consumer) WithContext(ctx context.Context) IConsumerDo { return c.consumerDo.WithContext(ctx) }

func (c consumer) TableName() string { return c.consumerDo.TableName() }

func (c consumer) Alias() string { return c.consumerDo.Alias() }

func (c consumer) Columns(cols ...field.Expr) gen.Columns { return c.consumerDo.Columns(cols...) }

func (c *consumer) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *consumer) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 11)
	c.fieldMap["id"] = c.ID
	c.fieldMap["name"] = c.Name
	c.fieldMap["enabled"] = c.Enabled
	c.fieldMap["metadata_json"] = c.MetadataJSON
	c.fieldMap["protocols_json"] = c.ProtocolsJSON
	c.fieldMap["ip_allowlist_json"] = c.IPAllowlistJSON
	c.fieldMap["max_input_tokens"] = c.MaxInputTokens
	c.fieldMap["max_output_tokens"] = c.MaxOutputTokens
	c.fieldMap["max_request_body_bytes"] = c.MaxRequestBodyBytes
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c consumer) clone(db *gorm.DB) consumer {
	c.consumerDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c consumer) replaceDB(db *gorm.DB) consumer {
	c.consumerDo.ReplaceDB(db)
	return c
}

type consumerDo struct{ gen.DO }

type IConsumerDo interface {
	gen.SubQuery
	Debug() IConsumerDo
	WithContext(ctx context.Context) IConsumerDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IConsumerDo
	WriteDB() IConsumerDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IConsumerDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IConsumerDo
	Not(conds ...gen.Condition) IConsumerDo
	Or(conds ...gen.Condition) IConsumerDo
	Select(conds ...field.Expr) IConsumerDo
	Where(conds ...gen.Condition) IConsumerDo
	Order(conds ...field.Expr) IConsumerDo
	Distinct(cols ...field.Expr) IConsumerDo
	Omit(cols ...field.Expr) IConsumerDo
	Join(table schema.Tabler, on ...field.Expr) IConsumerDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IConsumerDo
	RightJoin(table schema.Tabler, on ...field.Expr) IConsumerDo
	Group(cols ...field.Expr) IConsumerDo
	Having(conds ...gen.Condition) IConsumerDo
	Limit(limit int) IConsumerDo
	Offset(offset int) IConsumerDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IConsumerDo
	Unscoped() IConsumerDo
	Create(values ...*model.Consumer) error
	CreateInBatches(values []*model.Consumer, batchSize int) error
	Save(values ...*model.Consumer) error
	First() (*model.Consumer, error)
	Take() (*model.Consumer, error)
	Last() (*model.Consumer, error)
	Find() ([]*model.Consumer, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Consumer, err error)
	FindInBatches(result *[]*model.Consumer, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Consumer) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IConsumerDo
	Assign(attrs ...field.AssignExpr) IConsumerDo
	Joins(fields ...field.RelationField) IConsumerDo
	Preload(fields ...field.RelationField) IConsumerDo
	FirstOrInit() (*model.Consumer, error)
	FirstOrCreate() (*model.Consumer, error)
	FindByPage(offset int, limit int) (result []*model.Consumer, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IConsumerDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c consumerDo) Debug() IConsumerDo {
	return c.withDO(c.DO.Debug())
}

func (c consumerDo) WithContext(ctx context.Context) IConsumerDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c consumerDo) ReadDB() IConsumerDo {
	return c.Clauses(dbresolver.Read)
}

func (c consumerDo) WriteDB() IConsumerDo {
	return c.Clauses(dbresolver.Write)
}

func (c consumerDo) Session(config *gorm.Session) IConsumerDo {
	return c.withDO(c.DO.Session(config))
}

func (c consumerDo) Clauses(conds ...clause.Expression) IConsumerDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c consumerDo) Returning(value interface{}, columns ...string) IConsumerDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c consumerDo) Not(conds ...gen.Condition) IConsumerDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c consumerDo) Or(conds ...gen.Condition) IConsumerDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c consumerDo) Select(conds ...field.Expr) IConsumerDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c consumerDo) Where(conds ...gen.Condition) IConsumerDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c consumerDo) Order(conds ...field.Expr) IConsumerDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c consumerDo) Distinct(cols ...field.Expr) IConsumerDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c consumerDo) Omit(cols ...field.Expr) IConsumerDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c consumerDo) Join(table schema.Tabler, on ...field.Expr) IConsumerDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c consumerDo) LeftJoin(table schema.Tabler, on ...field.Expr) IConsumerDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c consumerDo) RightJoin(table schema.Tabler, on ...field.Expr) IConsumerDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c consumerDo) Group(cols ...field.Expr) IConsumerDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c consumerDo) Having(conds ...gen.Condition) IConsumerDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c consumerDo) Limit(limit int) IConsumerDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c consumerDo) Offset(offset int) IConsumerDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c consumerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IConsumerDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c consumerDo) Unscoped() IConsumerDo {
	return c.withDO(c.DO.Unscoped())
}

func (c consumerDo) Create(values ...*model.Consumer) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c consumerDo) CreateInBatches(values []*model.Consumer, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c consumerDo) Save(values ...*model.Consumer) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c consumerDo) First() (*model.Consumer, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Consumer), nil
	}
}

func (c consumerDo) Take() (*model.Consumer, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Consumer), nil
	}
}

func (c consumerDo) Last() (*model.Consumer, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Consumer), nil
	}
}

func (c consumerDo) Find() ([]*model.Consumer, error) {
	result, err := c.DO.Find()
	return result.([]*model.Consumer), err
}

func (c consumerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Consumer, err error) {
	buf := make([]*model.Consumer, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c consumerDo) FindInBatches(result *[]*model.Consumer, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c consumerDo) Attrs(attrs ...field.AssignExpr) IConsumerDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c consumerDo) Assign(attrs ...field.AssignExpr) IConsumerDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c consumerDo) Joins(fields ...field.RelationField) IConsumerDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c consumerDo) Preload(fields ...field.RelationField) IConsumerDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c consumerDo) FirstOrInit() (*model.Consumer, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Consumer), nil
	}
}

func (c consumerDo) FirstOrCreate() (*model.Consumer, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Consumer), nil
	}
}

func (c consumerDo) FindByPage(offset int, limit int) (result []*model.Consumer, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c consumerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c consumerDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c consumerDo) Delete(models ...*model.Consumer) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *consumerDo) withDO(do gen.Dao) *consumerDo {
	c.DO = *do.(*gen.DO)
	return c
}
