// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/nyroway/nyro/go/internal/storage/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newConsumerQuota(db *gorm.DB, opts ...gen.DOOption) consumerQuota {
	_consumerQuota := consumerQuota{}

	_consumerQuota.consumerQuotaDo.UseDB(db, opts...)
	_consumerQuota.consumerQuotaDo.UseModel(&model.ConsumerQuota{})

	tableName := _consumerQuota.consumerQuotaDo.TableName()
	_consumerQuota.ALL = field.NewAsterisk(tableName)
	_consumerQuota.ID = field.NewString(tableName, "id")
	_consumerQuota.ConsumerID = field.NewString(tableName, "consumer_id")
	_consumerQuota.QuotaType = field.NewString(tableName, "quota_type")
	_consumerQuota.QuotaLimit = field.NewInt64(tableName, "quota_limit")
	_consumerQuota.Window = field.NewString(tableName, "window")
	_consumerQuota.Currency = field.NewString(tableName, "currency")
	_consumerQuota.CreatedAt = field.NewString(tableName, "created_at")
	_consumerQuota.UpdatedAt = field.NewString(tableName, "updated_at")

	_consumerQuota.fillFieldMap()

	return _consumerQuota
}

type consumerQuota struct {
	consumerQuotaDo consumerQuotaDo

	ALL        field.Asterisk
	ID         field.String
	ConsumerID field.String
	QuotaType  field.String
	QuotaLimit field.Int64
	Window     field.String
	Currency   field.String
	CreatedAt  field.String
	UpdatedAt  field.String

	fieldMap map[string]field.Expr
}

func (c consumerQuota) Table(newTableName string) *consumerQuota {
	c.consumerQuotaDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c consumerQuota) As(alias string) *consumerQuota {
	c.consumerQuotaDo.DO = *(c.consumerQuotaDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *consumerQuota) updateTableName(table string) *consumerQuota {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.ConsumerID = field.NewString(table, "consumer_id")
	c.QuotaType = field.NewString(table, "quota_type")
	c.QuotaLimit = field.NewInt64(table, "quota_limit")
	c.Window = field.NewString(table, "window")
	c.Currency = field.NewString(table, "currency")
	c.CreatedAt = field.NewString(table, "created_at")
	c.UpdatedAt = field.NewString(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *consumerQuota) WithContext(ctx context.Context) IConsumerQuotaDo {
	return c.consumerQuotaDo.WithContext(ctx)
}

func (c consumerQuota) TableName() string { return c.consumerQuotaDo.TableName() }

func (c consumerQuota) Alias() string { return c.consumerQuotaDo.Alias() }

func (c consumerQuota) Columns(cols ...field.Expr) gen.Columns {
	return c.consumerQuotaDo.Columns(cols...)
}

func (c *consumerQuota) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *consumerQuota) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 8)
	c.fieldMap["id"] = c.ID
	c.fieldMap["consumer_id"] = c.ConsumerID
	c.fieldMap["quota_type"] = c.QuotaType
	c.fieldMap["quota_limit"] = c.QuotaLimit
	c.fieldMap["window"] = c.Window
	c.fieldMap["currency"] = c.Currency
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c consumerQuota) clone(db *gorm.DB) consumerQuota {
	c.consumerQuotaDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c consumerQuota) replaceDB(db *gorm.DB) consumerQuota {
	c.consumerQuotaDo.ReplaceDB(db)
	return c
}

type consumerQuotaDo struct{ gen.DO }

type IConsumerQuotaDo interface {
	gen.SubQuery
	Debug() IConsumerQuotaDo
	WithContext(ctx context.Context) IConsumerQuotaDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IConsumerQuotaDo
	WriteDB() IConsumerQuotaDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IConsumerQuotaDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IConsumerQuotaDo
	Not(conds ...gen.Condition) IConsumerQuotaDo
	Or(conds ...gen.Condition) IConsumerQuotaDo
	Select(conds ...field.Expr) IConsumerQuotaDo
	Where(conds ...gen.Condition) IConsumerQuotaDo
	Order(conds ...field.Expr) IConsumerQuotaDo
	Distinct(cols ...field.Expr) IConsumerQuotaDo
	Omit(cols ...field.Expr) IConsumerQuotaDo
	Join(table schema.Tabler, on ...field.Expr) IConsumerQuotaDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IConsumerQuotaDo
	RightJoin(table schema.Tabler, on ...field.Expr) IConsumerQuotaDo
	Group(cols ...field.Expr) IConsumerQuotaDo
	Having(conds ...gen.Condition) IConsumerQuotaDo
	Limit(limit int) IConsumerQuotaDo
	Offset(offset int) IConsumerQuotaDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IConsumerQuotaDo
	Unscoped() IConsumerQuotaDo
	Create(values ...*model.ConsumerQuota) error
	CreateInBatches(values []*model.ConsumerQuota, batchSize int) error
	Save(values ...*model.ConsumerQuota) error
	First() (*model.ConsumerQuota, error)
	Take() (*model.ConsumerQuota, error)
	Last() (*model.ConsumerQuota, error)
	Find() ([]*model.ConsumerQuota, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ConsumerQuota, err error)
	FindInBatches(result *[]*model.ConsumerQuota, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ConsumerQuota) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IConsumerQuotaDo
	Assign(attrs ...field.AssignExpr) IConsumerQuotaDo
	Joins(fields ...field.RelationField) IConsumerQuotaDo
	Preload(fields ...field.RelationField) IConsumerQuotaDo
	FirstOrInit() (*model.ConsumerQuota, error)
	FirstOrCreate() (*model.ConsumerQuota, error)
	FindByPage(offset int, limit int) (result []*model.ConsumerQuota, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IConsumerQuotaDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c consumerQuotaDo) Debug() IConsumerQuotaDo {
	return c.withDO(c.DO.Debug())
}

func (c consumerQuotaDo) WithContext(ctx context.Context) IConsumerQuotaDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c consumerQuotaDo) ReadDB() IConsumerQuotaDo {
	return c.Clauses(dbresolver.Read)
}

func (c consumerQuotaDo) WriteDB() IConsumerQuotaDo {
	return c.Clauses(dbresolver.Write)
}

func (c consumerQuotaDo) Session(config *gorm.Session) IConsumerQuotaDo {
	return c.withDO(c.DO.Session(config))
}

func (c consumerQuotaDo) Clauses(conds ...clause.Expression) IConsumerQuotaDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c consumerQuotaDo) Returning(value interface{}, columns ...string) IConsumerQuotaDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c consumerQuotaDo) Not(conds ...gen.Condition) IConsumerQuotaDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c consumerQuotaDo) Or(conds ...gen.Condition) IConsumerQuotaDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c consumerQuotaDo) Select(conds ...field.Expr) IConsumerQuotaDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c consumerQuotaDo) Where(conds ...gen.Condition) IConsumerQuotaDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c consumerQuotaDo) Order(conds ...field.Expr) IConsumerQuotaDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c consumerQuotaDo) Distinct(cols ...field.Expr) IConsumerQuotaDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c consumerQuotaDo) Omit(cols ...field.Expr) IConsumerQuotaDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c consumerQuotaDo) Join(table schema.Tabler, on ...field.Expr) IConsumerQuotaDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c consumerQuotaDo) LeftJoin(table schema.Tabler, on ...field.Expr) IConsumerQuotaDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c consumerQuotaDo) RightJoin(table schema.Tabler, on ...field.Expr) IConsumerQuotaDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c consumerQuotaDo) Group(cols ...field.Expr) IConsumerQuotaDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c consumerQuotaDo) Having(conds ...gen.Condition) IConsumerQuotaDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c consumerQuotaDo) Limit(limit int) IConsumerQuotaDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c consumerQuotaDo) Offset(offset int) IConsumerQuotaDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c consumerQuotaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IConsumerQuotaDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c consumerQuotaDo) Unscoped() IConsumerQuotaDo {
	return c.withDO(c.DO.Unscoped())
}

func (c consumerQuotaDo) Create(values ...*model.ConsumerQuota) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c consumerQuotaDo) CreateInBatches(values []*model.ConsumerQuota, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c consumerQuotaDo) Save(values ...*model.ConsumerQuota) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c consumerQuotaDo) First() (*model.ConsumerQuota, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConsumerQuota), nil
	}
}

func (c consumerQuotaDo) Take() (*model.ConsumerQuota, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConsumerQuota), nil
	}
}

func (c consumerQuotaDo) Last() (*model.ConsumerQuota, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConsumerQuota), nil
	}
}

func (c consumerQuotaDo) Find() ([]*model.ConsumerQuota, error) {
	result, err := c.DO.Find()
	return result.([]*model.ConsumerQuota), err
}

func (c consumerQuotaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ConsumerQuota, err error) {
	buf := make([]*model.ConsumerQuota, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c consumerQuotaDo) FindInBatches(result *[]*model.ConsumerQuota, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c consumerQuotaDo) Attrs(attrs ...field.AssignExpr) IConsumerQuotaDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c consumerQuotaDo) Assign(attrs ...field.AssignExpr) IConsumerQuotaDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c consumerQuotaDo) Joins(fields ...field.RelationField) IConsumerQuotaDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c consumerQuotaDo) Preload(fields ...field.RelationField) IConsumerQuotaDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c consumerQuotaDo) FirstOrInit() (*model.ConsumerQuota, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConsumerQuota), nil
	}
}

func (c consumerQuotaDo) FirstOrCreate() (*model.ConsumerQuota, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConsumerQuota), nil
	}
}

func (c consumerQuotaDo) FindByPage(offset int, limit int) (result []*model.ConsumerQuota, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c consumerQuotaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c consumerQuotaDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c consumerQuotaDo) Delete(models ...*model.ConsumerQuota) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *consumerQuotaDo) withDO(do gen.Dao) *consumerQuotaDo {
	c.DO = *do.(*gen.DO)
	return c
}
