// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/nyroway/nyro/go/internal/storage/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newUpstream(db *gorm.DB, opts ...gen.DOOption) upstream {
	_upstream := upstream{}

	_upstream.upstreamDo.UseDB(db, opts...)
	_upstream.upstreamDo.UseModel(&model.Upstream{})

	tableName := _upstream.upstreamDo.TableName()
	_upstream.ALL = field.NewAsterisk(tableName)
	_upstream.ID = field.NewString(tableName, "id")
	_upstream.Name = field.NewString(tableName, "name")
	_upstream.Protocol = field.NewString(tableName, "protocol")
	_upstream.BaseURL = field.NewString(tableName, "base_url")
	_upstream.CredentialsJSON = field.NewString(tableName, "credentials_json")
	_upstream.ModelsJSON = field.NewString(tableName, "models_json")
	_upstream.ProxyURL = field.NewString(tableName, "proxy_url")
	_upstream.Enabled = field.NewBool(tableName, "enabled")
	_upstream.CreatedAt = field.NewString(tableName, "created_at")
	_upstream.UpdatedAt = field.NewString(tableName, "updated_at")

	_upstream.fillFieldMap()

	return _upstream
}

type upstream struct {
	upstreamDo upstreamDo

	ALL             field.Asterisk
	ID              field.String
	Name            field.String
	Protocol        field.String
	BaseURL         field.String
	CredentialsJSON field.String
	ModelsJSON      field.String
	ProxyURL        field.String
	Enabled         field.Bool
	CreatedAt       field.String
	UpdatedAt       field.String

	fieldMap map[string]field.Expr
}

func (u upstream) Table(newTableName string) *upstream {
	u.upstreamDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u upstream) As(alias string) *upstream {
	u.upstreamDo.DO = *(u.upstreamDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *upstream) updateTableName(table string) *upstream {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewString(table, "id")
	u.Name = field.NewString(table, "name")
	u.Protocol = field.NewString(table, "protocol")
	u.BaseURL = field.NewString(table, "base_url")
	u.CredentialsJSON = field.NewString(table, "credentials_json")
	u.ModelsJSON = field.NewString(table, "models_json")
	u.ProxyURL = field.NewString(table, "proxy_url")
	u.Enabled = field.NewBool(table, "enabled")
	u.CreatedAt = field.NewString(table, "created_at")
	u.UpdatedAt = field.NewString(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *upstream) WithContext(ctx context.Context) IUpstreamDo { return u.upstreamDo.WithContext(ctx) }

func (u upstream) TableName() string { return u.upstreamDo.TableName() }

func (u upstream) Alias() string { return u.upstreamDo.Alias() }

func (u upstream) Columns(cols ...field.Expr) gen.Columns { return u.upstreamDo.Columns(cols...) }

func (u *upstream) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *upstream) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 10)
	u.fieldMap["id"] = u.ID
	u.fieldMap["name"] = u.Name
	u.fieldMap["protocol"] = u.Protocol
	u.fieldMap["base_url"] = u.BaseURL
	u.fieldMap["credentials_json"] = u.CredentialsJSON
	u.fieldMap["models_json"] = u.ModelsJSON
	u.fieldMap["proxy_url"] = u.ProxyURL
	u.fieldMap["enabled"] = u.Enabled
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u upstream) clone(db *gorm.DB) upstream {
	u.upstreamDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u upstream) replaceDB(db *gorm.DB) upstream {
	u.upstreamDo.ReplaceDB(db)
	return u
}

type upstreamDo struct{ gen.DO }

type IUpstreamDo interface {
	gen.SubQuery
	Debug() IUpstreamDo
	WithContext(ctx context.Context) IUpstreamDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUpstreamDo
	WriteDB() IUpstreamDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUpstreamDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUpstreamDo
	Not(conds ...gen.Condition) IUpstreamDo
	Or(conds ...gen.Condition) IUpstreamDo
	Select(conds ...field.Expr) IUpstreamDo
	Where(conds ...gen.Condition) IUpstreamDo
	Order(conds ...field.Expr) IUpstreamDo
	Distinct(cols ...field.Expr) IUpstreamDo
	Omit(cols ...field.Expr) IUpstreamDo
	Join(table schema.Tabler, on ...field.Expr) IUpstreamDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUpstreamDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUpstreamDo
	Group(cols ...field.Expr) IUpstreamDo
	Having(conds ...gen.Condition) IUpstreamDo
	Limit(limit int) IUpstreamDo
	Offset(offset int) IUpstreamDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUpstreamDo
	Unscoped() IUpstreamDo
	Create(values ...*model.Upstream) error
	CreateInBatches(values []*model.Upstream, batchSize int) error
	Save(values ...*model.Upstream) error
	First() (*model.Upstream, error)
	Take() (*model.Upstream, error)
	Last() (*model.Upstream, error)
	Find() ([]*model.Upstream, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Upstream, err error)
	FindInBatches(result *[]*model.Upstream, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Upstream) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUpstreamDo
	Assign(attrs ...field.AssignExpr) IUpstreamDo
	Joins(fields ...field.RelationField) IUpstreamDo
	Preload(fields ...field.RelationField) IUpstreamDo
	FirstOrInit() (*model.Upstream, error)
	FirstOrCreate() (*model.Upstream, error)
	FindByPage(offset int, limit int) (result []*model.Upstream, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUpstreamDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u upstreamDo) Debug() IUpstreamDo {
	return u.withDO(u.DO.Debug())
}

func (u upstreamDo) WithContext(ctx context.Context) IUpstreamDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u upstreamDo) ReadDB() IUpstreamDo {
	return u.Clauses(dbresolver.Read)
}

func (u upstreamDo) WriteDB() IUpstreamDo {
	return u.Clauses(dbresolver.Write)
}

func (u upstreamDo) Session(config *gorm.Session) IUpstreamDo {
	return u.withDO(u.DO.Session(config))
}

func (u upstreamDo) Clauses(conds ...clause.Expression) IUpstreamDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u upstreamDo) Returning(value interface{}, columns ...string) IUpstreamDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u upstreamDo) Not(conds ...gen.Condition) IUpstreamDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u upstreamDo) Or(conds ...gen.Condition) IUpstreamDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u upstreamDo) Select(conds ...field.Expr) IUpstreamDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u upstreamDo) Where(conds ...gen.Condition) IUpstreamDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u upstreamDo) Order(conds ...field.Expr) IUpstreamDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u upstreamDo) Distinct(cols ...field.Expr) IUpstreamDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u upstreamDo) Omit(cols ...field.Expr) IUpstreamDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u upstreamDo) Join(table schema.Tabler, on ...field.Expr) IUpstreamDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u upstreamDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUpstreamDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u upstreamDo) RightJoin(table schema.Tabler, on ...field.Expr) IUpstreamDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u upstreamDo) Group(cols ...field.Expr) IUpstreamDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u upstreamDo) Having(conds ...gen.Condition) IUpstreamDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u upstreamDo) Limit(limit int) IUpstreamDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u upstreamDo) Offset(offset int) IUpstreamDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u upstreamDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUpstreamDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u upstreamDo) Unscoped() IUpstreamDo {
	return u.withDO(u.DO.Unscoped())
}

func (u upstreamDo) Create(values ...*model.Upstream) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u upstreamDo) CreateInBatches(values []*model.Upstream, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u upstreamDo) Save(values ...*model.Upstream) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u upstreamDo) First() (*model.Upstream, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Upstream), nil
	}
}

func (u upstreamDo) Take() (*model.Upstream, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Upstream), nil
	}
}

func (u upstreamDo) Last() (*model.Upstream, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Upstream), nil
	}
}

func (u upstreamDo) Find() ([]*model.Upstream, error) {
	result, err := u.DO.Find()
	return result.([]*model.Upstream), err
}

func (u upstreamDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Upstream, err error) {
	buf := make([]*model.Upstream, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u upstreamDo) FindInBatches(result *[]*model.Upstream, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u upstreamDo) Attrs(attrs ...field.AssignExpr) IUpstreamDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u upstreamDo) Assign(attrs ...field.AssignExpr) IUpstreamDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u upstreamDo) Joins(fields ...field.RelationField) IUpstreamDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u upstreamDo) Preload(fields ...field.RelationField) IUpstreamDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u upstreamDo) FirstOrInit() (*model.Upstream, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Upstream), nil
	}
}

func (u upstreamDo) FirstOrCreate() (*model.Upstream, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Upstream), nil
	}
}

func (u upstreamDo) FindByPage(offset int, limit int) (result []*model.Upstream, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u upstreamDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u upstreamDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u upstreamDo) Delete(models ...*model.Upstream) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *upstreamDo) withDO(do gen.Dao) *upstreamDo {
	u.DO = *do.(*gen.DO)
	return u
}
