package ir

// ServerToolUsage counts server-side tool calls (web search, web fetch).
type ServerToolUsage struct {
	WebSearchRequests uint32
	WebFetchRequests  uint32
}

// Usage holds token usage statistics for a request/response pair.
//
// Field naming follows IR conventions:
//   - PromptTokens     — input tokens (prompt + cached context)
//   - CompletionTokens — output tokens generated by the model
//   - TotalTokens      — prompt + completion (may be 0 if not supplied)
//   - CacheReadTokens  — tokens served from the prompt cache
//   - CacheCreationTokens — tokens written to the prompt cache
//   - ServerToolUse    — server-side tool call counts
//
// Optional counters use pointers to distinguish unset from zero.
type Usage struct {
	PromptTokens        uint32
	CompletionTokens    uint32
	TotalTokens         uint32
	CacheReadTokens     *uint32
	CacheCreationTokens *uint32
	ServerToolUse       *ServerToolUsage
}
