// Package migrations embeds the versioned mysql/postgres schema migrations
// generated by `make go-migrate-diff` (see ../atlas.hcl), so the compiled
// nyro binary carries a fixed "expected schema version" without depending on
// this source tree being present at runtime. sqlite has no migrations here —
// it stays on GORM AutoMigrate.
package migrations

import (
	"embed"
	"fmt"
	"sort"
	"strings"
)

//go:embed mysql/*.sql postgres/*.sql
var FS embed.FS

// LatestVersion returns the version identifier (the leading timestamp, e.g.
// "20260713135351") of the newest migration file for dialect ("mysql" or
// "postgres"). internal/bootstrap compares this against the version
// recorded in atlas_schema_revisions to fail fast on a schema mismatch.
func LatestVersion(dialect string) (string, error) {
	entries, err := FS.ReadDir(dialect)
	if err != nil {
		return "", fmt.Errorf("read embedded migrations for %s: %w", dialect, err)
	}
	var versions []string
	for _, e := range entries {
		version, _, ok := strings.Cut(e.Name(), "_")
		if !ok || !strings.HasSuffix(e.Name(), ".sql") {
			continue
		}
		versions = append(versions, version)
	}
	if len(versions) == 0 {
		return "", fmt.Errorf("no migration files embedded for %s", dialect)
	}
	sort.Strings(versions)
	return versions[len(versions)-1], nil
}
